# File: structured_output.py

from pydantic import BaseModel, Field
from typing import List
# 新增：用于 ToolRetriever 的结构化输出
# --- model/structured_output.py ---

# --- model/structured_output.py ---
from pydantic import BaseModel, Field
from typing import List

class SelectedResources(BaseModel):
    """
    Represents the list of resource indices selected by the ToolRetriever.
    The reasoning field forces the LLM to think before selecting indices.
    """
    # 核心改动：增加推理字段
    reasoning: str = Field(description="Briefly explain the logic for choosing these tools based on the user's biological context.")
    
    tools: List[int] = Field(default_factory=list, description="Selected indices (integers) from the list of available tools.")
    data_lake: List[int] = Field(default_factory=list, description="Selected indices (integers) from the list of available data lakes.")
    libraries: List[int] = Field(default_factory=list, description="Selected indices (integers) from the list of available libraries.")
    know_how: List[int] = Field(default_factory=list, description="Selected indices (integers) from the list of Know-How documents.")
# Defines one step in the plan
class AnalysisStep(BaseModel):
    """Represents a single, actionable step in the structured analysis plan."""
    step_number: int = Field(..., description="The sequential number of the step (starting from 1).")
    title: str = Field(..., description="A short, descriptive title for the step (e.g., Data QC and Normalization, or: TP53 sgRNA Screening).")
    description: str = Field(..., description="Details the operations for this step, the Know-How documents that should be referenced, the tools used, and the expected results.")
    tool_or_function: str = Field(..., description="The name of the main tool, Python library (e.g., Scanpy, pandas), or CLI tool (e.g., plink2) this step relies on. Write 'N/A' if it is only a thought or summary step.")

# Defines the final structured analysis plan
class StructuredAnalysisPlan(BaseModel):
    """The final structured analysis plan generated by the Planner Agent."""
    
    retrieval_reasoning: str = Field(..., description="Briefly explain why these Know-How documents and tools were selected, and how they work together to solve the user's problem.")
    analysis_roadmap: str = Field(..., description="Outlines the high-level analysis process and methodology, serving as an overview of the detailed steps (e.g., Three-stage CRISPRko sgRNA design workflow).")
    plan_steps: List[AnalysisStep] = Field(..., description="The detailed, step-by-step list of the analysis plan.")